config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
end


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :user do
      root to: 'homes#top'
      resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :plan_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
      resources :spots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :spot_comments, only: [:create, :destroy]
    end
      resources :contacts, only: [:new, :create, :index, :show, :update, :destroy]
      get '/spots/:id/status' => 'spots#status', as: 'status'
      resources :users, only: [:show, :edit, :update]
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resources :perfectures, only: [:show]
      get '/plans/search' => 'plans#search', as: 'search_result'
      get '/searches/search_spot' => 'searches#search_spot', as: 'search'
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :contacts, only: [:index, :show]
    resources :spots, only: [:index, :show]
    resources :plans, only: [:index, :show]
    resources :perfectures, only: [:index, :create, :edit, :update, :destroy]
    get 'admin/searches/search' => 'searches#search', as: 'search'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_one_attached :profile_image
  has_many :plans, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :plan_comments, dependent: :destroy
  has_many :spot_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :contacts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :profile, length: { maximum: 200 }

 #検索
  def self.looks(search, word)
    if search == "perfect_match"
      @search_users = User.where("name or id LIKE?", "#{word}")
    elsif search == "partial_match"
      @search_users = User.where("name or id LIKE?","%#{word}%")
    else
      @search_users = User.all
    end
  end

  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      file_path = Rails.root.join('app/assets/images/noimage.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  end

  #ゲストログイン
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  #退会後同じアカウントでログインできないようにする
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  before_action :admin_scan, only: [:index]

  def index
    @plans = Plan.all.page(params[:page]).per(20).order(created_at: :desc)
  end
  
  private
  
  def admin_scan
   unless admin_signed_in?
     redirect_to root_path
   end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_action :admin_scan, only: [:index]
  def index
    @users = User.all.page(params[:page]).per(10).order(created_at: :desc)
  end

 private

  def admin_scan
   unless admin_signed_in?
     redirect_to root_path
   end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  before_action :user_scan, only: [:new]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      UserMailer.contact_email(@contact, @user).deliver
      flash[:notice] = "お問合せ内容を送信しました。回答はメールでお送りします。"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def update
    @contact = Contact.find(params[:id])
    @user = @contact.user
    if @contact.update(contact_params)
      UserMailer.update_email(@contact, @user).deliver
      flash[:notice] = "情報を更新しました。"
       redirect_to admin_contacts_path
    else
       render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
      flash[:notice] = "削除しました。"
      redirect_to '/admin/contacts'
  end

  def user_scan
   unless user_signed_in?
     redirect_to root_path
   end
  end

  private

  def contact_params
    params.require(:contact).permit(:kinds, :subject, :contact_status, :message)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    @plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.new(plan_id: @plan.id)
    favorite.save
  end

  def destroy
    @plan = Plan.find(params[:plan_id])
    favorite = current_user.favorites.find_by(plan_id: @plan.id)
    favorite.destroy
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @perfectures = Perfecture.all
    @plans = Plan.includes(:favorited_users).limit(10).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/perfectures_controller.rb
class User::PerfecturesController < ApplicationController
  def show
    @perfectures = Perfecture.all
    @perfecture = Perfecture.find(params[:id])
    @favorites = @perfecture.plans.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end
end

app/controllers/user/plan_comments_controller.rb
class User::PlanCommentsController < ApplicationController
  def create
    @plan = Plan.find(params[:plan_id])
    @comment = current_user.plan_comments.new(plan_comment_params)
    @comment.plan_id = @plan.id
    @comment.save

  end

  def destroy
    PlanComment.find(params[:id]).destroy
    @plan = Plan.find(params[:plan_id])

  end

  private

  def plan_comment_params
    params.require(:plan_comment).permit(:comment)
  end
end

app/controllers/user/plans_controller.rb
class User::PlansController < ApplicationController
  def new
    @plan = Plan.new
    @perfectures = Perfecture.all
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    if @plan.save
      flash[:notice] = "投稿しました。"
      redirect_to plans_path
    else
      render :new
    end
  end

  def index
    @plans = Plan.all.order(created_at: :desc).page(params[:page]).per(20).order(created_at: :desc)
    @favorites = @search_plans.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @perfectures = Perfecture.all
  end

  def show
    @plan = Plan.find(params[:id])
    if user_signed_in?
      unless ViewCount.find_by(user_id: current_user.id, plan_id: @plan.id)
        current_user.view_counts.create(plan_id: @plan.id)
      end
    end
    @perfectures = Perfecture.all
    @comment = PlanComment.new
  end

  def edit
     @plan = Plan.find(params[:id])
    if @plan.user == current_user
      render "edit"
    else
    redirect_to plans_path
    end
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      flash[:notice] = "投稿内容の修正が正常に完了しました。"
       redirect_to plan_path(@plan.id)
    else
       render :edit
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    if user_signed_in?
      redirect_to '/plans'
    else
      redirect_to '/admin/plans'
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:user_id, :situation, :perfecture_id, :start_image, :gole_image, :start, :gole, :start_introduction, :gole_introduction, :minutes, :attention,
                                  ##planでrelayのカラムを保存するための記述
                                  relays_attributes:[:id, :relay_point, :point_introduction, :image, :travel_time, :travel_attention, :_destroy])
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_in_path_for(resource)
      plans_path
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  def search_spot
      @search_spots = Spot.looks(params[:search], params[:word])
      @perfectures = Perfecture.all
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end

  private

  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && @user.is_deleted
        redirect_to new_user_session_path, notice: "退会済みです。再度ご登録をお願いいたします。"
      end
    end
  end

  def after_sign_in_path_for(resource)
      plans_path
  end
end

app/controllers/user/spot_comments_controller.rb
class User::SpotCommentsController < ApplicationController
  def create
    @spot = Spot.find(params[:spot_id])
    @comment = current_user.spot_comments.new(spot_comment_params)
    @comment.spot_id = @spot.id
    @comment.save

  end

  def destroy
    SpotComment.find(params[:id]).destroy
    @spot = Spot.find(params[:spot_id])

  end

  private

  def spot_comment_params
    params.require(:spot_comment).permit(:comment, :rate, spot_images: [])
  end
end

app/controllers/user/spots_controller.rb
class User::SpotsController < ApplicationController
  def new
    @spot = Spot.new
    @perfectures = Perfecture.all
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.user_id = current_user.id
    if @spot.save
      UserMailer.status_email(@spot, @user).deliver
      flash[:notice] = "投稿しました。審査結果はご登録済みのメールアドレスに送信されます。"
      redirect_to status_path(current_user)
    else
      render :new
    end
  end

  def index
    @spots = Spot.where(status: 1).order(created_at: :desc).page(params[:page]).per(12).order(created_at: :desc)
    @perfectures = Perfecture.all
  end

  def status
    @user = User.find(params[:id])
    @spots = @user.spots.order(created_at: :desc).page(params[:page]).per(10).order(created_at: :desc)
    @perfectures = Perfecture.all
  end

  def show
    @spot = Spot.find(params[:id])
    @rate = @spot.spot_comments.average(:rate)
    @user = @spot.user
    @perfectures = Perfecture.all
    @comment = SpotComment.new
  end

  def edit
    @spot = Spot.find(params[:id])
    if @spot.user == current_user
      render "edit"
    else
    redirect_to spots_path
    end
  end

  def update
    @spot = Spot.find(params[:id])
    @user = @spot.user
    if @spot.update(spot_params)
      UserMailer.approval_email(@spot, @user).deliver
      flash[:notice] = "情報を更新しました。"
       redirect_to admin_spots_path
    else
       render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @user = current_user
    @spot.destroy
    if user_signed_in?
      redirect_to status_path(@user)
    else
      UserMailer.rejected_email(@spot, @user).deliver
      redirect_to '/admin/spots'
    end
  end

  private

  def spot_params
    params.require(:spot).permit(:address, :lat, :lng, :name, :perfecture_id, :status, images: [])
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :current_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @plans = @user.plans
    @spot = @user.spots.where(status: 0)
    #idに紐づくユーザーがお気に入り登録した情報のみを集める
    favorites = Favorite.where(user_id: @user.id).pluck(:plan_id)
    @favorites = Plan.find(favorites)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールが更新されました"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  #退会機能
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
     if user_signed_in?
      reset_session
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to root_path
     else
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to '/admin/users'
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :profile, :email)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/views/user/plans/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>投稿者 <i class="fa-solid fa-user"></i></th>
      <th>都道府県 <i class="fa-sharp fa-solid fa-map-pin"></i></th>
      <th>スタート <i class="fa-solid fa-car-side"></i></th>
      <th></th>
      <th>ゴール <i class="fa-solid fa-flag-checkered"></i></th>
      <th>お気に入り数 <i class="fa-solid fa-star"></i></th>
      <th>詳細 <i class="fa-regular fa-map"></i></th>
    </tr>
  </thead>
  <tbody>
    <% plans.each do |plan| %>
    <tr>
      <td class="text-left">
          <%= link_to(plan.user) do %>
          <%= image_tag plan.user.get_profile_image.variant(resize: '70x70') %>
          <% end %>
          <%= plan.user.name %>
      </td>
      <td><%= plan.perfecture.name %></td>
      <td><%= plan.start %></td>
      <td><i class="fa-solid fa-arrow-right"></i></td>
      <td><%= plan.gole %></td>
      <td><i class="fa-regular fa-star"></i><%= plan.favorites.count %></td>
      <td><%= link_to "詳細情報", plan_path(plan.id) %></td>
    <% end %>
  </tbody>
</table>

app/views/user/plans/_perfecture.html.erb
<table class="perfecture-table table table-bordered table-hover">
  <thead class="perfecture">
    <tr>
      <th class="active table-active">新規投稿</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to 'プランを投稿', new_plan_path, class:"ec-genre-list-item text-dark" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to 'スポットを申請', new_spot_path, class:"ec-genre-list-item text-dark" %>
      </td>
    </tr>
  </tbody>
</table>
<div class="search_form">
  <table class="perfecture-table table table-bordered table-hover">
    <thead class="perfecture">
      <tr>
        <th class="active table-active">スポット検索</th>
      </tr>
    </thead>
  </table>
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <div class="spot_form"><%= f.text_field :word %></div>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div onclick="obj=document.getElementById('perfecturelist').style; obj.display=(obj.display=='none')?'block':'none';">
  <table class="perfecture-table table table-bordered table-hover">
    <thead class="perfecture">
      <tr>
        <th class="active table-active">
          <a style="cursor:pointer;">都道府県スポット</a>
        </th>
      </tr>
    </thead>
  </table>
</div>

<div id="perfecturelist" style="display:none;clear:both;">
<table class="perfecture-table table table-bordered table-hover">
  <tbody>
    <% perfectures.each do |perfecture| %>
    <tr>
      <td>
        <%= link_to perfecture.name, perfecture_path(perfecture.id), class:"ec-genre-list-item text-dark"%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<table class="perfecture-table table table-bordered table-hover">
  <thead class="perfecture">
    <tr>
      <th class="active table-active">お問合せ</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to 'お問合せフォーム', new_contact_path, class:"ec-genre-list-item text-dark" %>
      </td>
    </tr>
  </tbody>
</table>

app/views/user/plans/_relay_fields.html.erb
<div class="nested-fields">
    <div>中継スポット名　※入力必須</div>
    <div class="plan_form"><%= f.text_field :relay_point, class: "form-control start" %></div>

    <div>現地の写真</div>
    <div class="plan_form"><%= f.file_field :image, class: "form-control-file image", accept: 'image/*' %></div>

    <div>おすすめポイント！　※最大140字</div>
    <div class="plan_form"><%= f.text_area :point_introduction, class: "form-control point_introduction" %></div>

    <div class="plan_form">次のポイントまでの移動時間：約<%= f.select :travel_time,*[1..59], class: "form-control travel_time" %>分</div>

    <div>道中気をつけた方がいい事やおすすめのルートがあれば教えてあげましょう！</div>
    <div class="plan_form"><%= f.text_area :travel_attention, class: "form-control travel_attention" %></div>

    <div><%= link_to_remove_association "中継ポイントを削除", f, class: "btn btn-secondary btn-block" %></div>
</div>

app/views/user/plans/_search.html.erb
<h3>都道府県から検索</h3>

<%= form_tag({controller:"plans",action:"index"}, method: :get) do %>

 <%= text_field_tag :search %>

 <%= submit_tag '検索する' %>

<% end %>

app/views/user/plans/show.html.erb
<div class="container">
  <div class="mx-auto">
    <div>
      <p id="notice" class="text-center"><%= notice %></p>
    </div>
  </div>
</div>
<div class="text-center">
<div class='container'>
  <div class='row'>
    <div class='col-lg-2 col-xs-12'>
      <div class="spotname"><%= render 'user/plans/perfecture', perfectures: @perfectures%></div>
    </div>

    <div class='col-lg-10 col-xs-10'>
  <div class="row">
    <div class="repoint">
    <div class='col-lg-7 col-xs-10'>
      <% if @plan.user == current_user %>
         <p class="view-count">足跡<i class="fa-solid fa-shoe-prints"></i>: <%= @plan.view_counts.count %></p>
         <div>
           <%= link_to "投稿内容を編集する", edit_plan_path(@plan), class:"btn btn-sm btn-success" %>
           <%= link_to "消去する", plan_path(@plan), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-sm btn-danger" %>
         </div>
      <% elsif admin_signed_in? %>
         <div>
           <%= link_to "消去する", plan_path(@plan), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-sm btn-danger" %>
         </div>
      <% else %>
      <% end %>
      <div class="area_space">
        投稿者：<%= image_tag @plan.user.get_profile_image.variant(resize: '70x70') %><%= @plan.user.name %>
      </div>
      <div>
        おすすめのシチュエーション<i class="fa-solid fa-car"></i> |<%= @plan.situation %>|
      </div>
      <!--スタート地点を表示-->
      <div class="area_space">
        <h3>スタート地点は<%= @plan.perfecture.name %>の<%= @plan.start %> <i class="fa-solid fa-car-side"></i></h3>
      </div>
      <div>
        <!--投稿されたスタート地点の写真-->
        <%= image_tag @plan.get_start_image(350,200) %>
      </div>
        <div>
          <h5 class="space">おすすめポイント <i class="fa-solid fa-bullhorn"></i><h5>
        </div>
        <div><%= @plan.start_introduction %></div>
      <div class="area_space">
        次のポイントまでの移動時間約は<%= @plan.minutes %>分
      </div>
      <div class="area_space">
          <h5>移動中の注意点 <i class="fa-solid fa-triangle-exclamation"></i><h5>
      </div>
        <% if @plan.attention.present? %>
        <p class="attention"><%= @plan.attention %></p>
        <% else %>
        <p>データがありません</p>
        <% end %>
      <div class="area_space">
        <h4><i class="fa-solid fa-person-running"></i><i class="fa-solid fa-arrow-down"></i></h4>
      </div>

      <!--中継地点を表示-->
      <% @plan.relays.each do |relay| %>
      <div class="area_space">
        <h3><th>中継ポイント<i class="fa-solid fa-location-dot"></i> <%= relay.relay_point %></th></h3>
      </div>
      <div>
        <!--投稿された中継地点の写真-->
        <%= image_tag relay.get_image(350,200) %>
      </div>
      <div>
        <h5 class="space">おすすめポイント <i class="fa-solid fa-bullhorn"></i><h5>
      </div>
        <div><%= relay.point_introduction %></div>
      <div class="area_space">
        次のポイントまでの移動時間は約<%= relay.travel_time %>分
      </div>
      <div class="area_space">
        <h5>移動中の注意点 <i class="fa-solid fa-triangle-exclamation"></i><h5>
      </div>
        <% if relay.travel_attention.present? %>
        <p><%= relay.travel_attention %></p>
        <% else %>
        <p>データがありません</p>
        <% end %>
      <div class="area_space">
        <h4><i class="fa-solid fa-person-running"></i><i class="fa-solid fa-arrow-down"></i></h4>
      </div>
      <% end %>

      <!--ゴール地点を表示-->
      <div class="area_space">
        <h3>ゴール<i class="fa-solid fa-flag-checkered"></i> <%= @plan.gole %></i><h3>
      </div>
      <div>
        <!--投稿されたゴール地点の写真-->
        <%= image_tag @plan.get_gole_image(350,200) %>
      </div>
      <div>
          <h5 class="space">おすすめポイント <i class="fa-solid fa-bullhorn"></i><h5>
      </div>
        <p><%= @plan.gole_introduction %></p>
    </div>

    <%if user_signed_in? %>
    <div class='col-lg-3 col-xs-10'>
      <div class="d-flex justify-content-center">
        <div class="favorite_buttons_<%= @plan.id %>">
          <div>
           <%= render 'user/favorites/favorite', plan: @plan %>
          </div>
        </div>
        <div>｜</div>
        <div>
          <div><%= @plan.plan_comments.count %>件のコメント｜</div>
        </div>
       </div>
    <% end %>
      <div class="d-flex justify-content-center">
        <div class="new-comment" style="width: 400px;#">
           <%= render 'user/plan_comments/form', plan: @plan, plan_comment: @comment %>
        </div>
      </div>
      <!--コメント一覧-->
        <div class="comments_area">
           <%= render 'user/plan_comments/plan_comment', plan: @plan %>
        </div>
    </div>
   </div>
  </div>
 </div>
</div>
</div>