config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
end


devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  scope module: :user do
      root to: 'homes#top'
      resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :plan_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
      resources :spots, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :spot_comments, only: [:create, :destroy]
    end
      resources :contacts, only: [:new, :create, :index, :show, :update, :destroy]
      get '/spots/:id/status' => 'spots#status', as: 'status'
      resources :users, only: [:show, :edit, :update]
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resources :perfectures, only: [:show]
      get '/plans/search' => 'plans#search', as: 'search_result'
      get '/searches/search_spot' => 'searches#search_spot', as: 'search'
  end

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :contacts, only: [:index, :show]
    resources :spots, only: [:index, :show]
    resources :plans, only: [:index, :show]
    resources :perfectures, only: [:index, :create, :edit, :update, :destroy]
    get 'admin/searches/search' => 'searches#search', as: 'search'
  end
end

app/models/perfecture.rb
class Perfecture < ApplicationRecord
  has_many :plans, dependent: :destroy
  has_many :spots, dependent: :destroy
end

app/controllers/admin/perfectures_controller.rb
class Admin::PerfecturesController < ApplicationController
before_action :admin_scan, only: [:index, :edit]
  def index
    @perfecture = Perfecture.new
    @perfectures = Perfecture.all
  end

  def create
    @perfecture = Perfecture.new(perfecture_params)
    if @perfecture .save
      redirect_to admin_perfectures_path
    else
      render :index
    end
  end

  def edit
     @perfecture = Perfecture.find(params[:id])
  end

  def update
    @perfecture = Perfecture.find(params[:id])
    if @perfecture.update(perfecture_params)
      flash[:notice] = "修正が正常に完了しました。"
       redirect_to admin_perfectures_path
    else
       render :edit
    end
  end

  def destroy
    @perfecture = Perfecture.find(params[:id])
    @perfecture.destroy
    redirect_to admin_perfectures_path
  end

    private

  def admin_scan
   unless admin_signed_in?
     redirect_to root_path
   end
  end

  def perfecture_params
    params.require(:perfecture).permit(:name)
  end

end

app/controllers/user/perfectures_controller.rb
class User::PerfecturesController < ApplicationController
  def show
    @perfectures = Perfecture.all
    @perfecture = Perfecture.find(params[:id])
    @favorites = @perfecture.plans.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end
end

app/helpers/admin/perfecture_helper.rb
module Admin::PerfectureHelper
end

app/helpers/admin/perfectures_helper.rb
module Admin::PerfecturesHelper
end

app/helpers/user/perfectures_helper.rb
module User::PerfecturesHelper
end

app/views/admin/perfectures/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 mx-auto">
      <h4 class="m-3"><strong>都道府県名編集</strong></h4>
      <%= form_with model: @perfecture, url: admin_perfecture_path, method: :patch do |f| %>
        <p class="my-5 mx-2">都道府県名
          <%= f.text_field :name, class: "mx-2" %>
          <%= f.submit '変更', class: "btn btn-success mx-2" %>
      <% end %>
          <%= link_to "消去する", admin_perfecture_path(@perfecture), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-sm btn-danger" %>
       </p>
    </div>
  </div>
</div>

app/views/admin/perfectures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 mx-auto">
      <h4 class="m-3"><strong>都道府県一覧</strong></h4>
      <%= form_with model:@perfecture, url: admin_perfectures_path, local:true do |f| %>
      <p class="my-5 mx-2">都道府県名
          <%= f.text_field :name, class: "mx-2" %>
          <%= f.submit '新規登録', class: "btn btn-success mx-2" %>
        </p>
      <% end %>

      <table class="table table-hover table-inverse shadow-lg">
        <thead>
          <tr>
            <th class="table-active">都道府県</th>
            <th class="table-active"></th>
          </tr>
        </thead>
        <tbody>
          <% @perfectures.each do |perfecture| %>
            <tr>
              <td>
                <%= perfecture.name %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_perfecture_path(perfecture.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>